cloudland/carts/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.cart, name='store-cart'),
    path('add/id=<int:id>', views.add_to_cart, name='add_to_cart'),
    path('remove/id=<int:id>', views.remove_from_cart, name='remove_from_cart'),
]

cloudland/cloudland/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("django.contrib.auth.urls")), # build in django auth urls
    path('', include('store.urls')),
    path('accounts/', include('accounts.urls')),
    path('cart/', include('carts.urls')),
    path('orders/', include('orders.urls')),
    path('sellers/', include('sellers.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cloudland/store/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.products_page_all, name='store-products-page-all-home-home'),
    path('products/search', views.products_search, name='store-products-search'),
    path('c/<slug:slug>', views.products_by_category, name='store-products-page-filter-category'),
    path('s/<slug:slug>', views.products_by_seller, name='store-products-page-filter-seller'),
    path('products/v/<slug:slug>', views.view_item, name='store-view-item'),
    path('products/r/<int:id>', views.post_review, name="post-review"),
    path('contact', views.contact, name='store-contact'),
    path('about', views.about, name='about'),
]

cloudland/store/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.utils.datetime_safe import datetime

from .utils import unique_slugify

class Seller(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True)
    profile_picture = models.ImageField(upload_to='seller_profiles', help_text="Upload your profile picture for our about page", blank=True, null=True)
    bio_description = models.TextField(max_length=500, default="", help_text="Brief bio describing who you are and what you do")
    seller_full_name = models.CharField(max_length=50)
    seller_listing_name = models.CharField(max_length=50)
    email = models.EmailField(max_length=50)
    date_added = models.DateField(auto_now_add=True)
    slug = models.SlugField(null=True, unique=True)
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return self.seller_listing_name


class Category(models.Model):
    name = models.CharField(max_length=30)
    slug = models.SlugField(null=False, unique=True)

    def __str__(self):
        return self.name
    
    class Meta:
        verbose_name_plural = "Categories"


# Create your models here.
class Product(models.Model):
    product_id = models.AutoField(primary_key=True)
    product_name = models.CharField(max_length=30, help_text="Limit 30 characters")
    slug = models.SlugField(unique=True, null=True)
    seller = models.ForeignKey(Seller, on_delete=models.CASCADE, null=True, blank=True)
    category = models.ManyToManyField(Category, help_text="Hold down “Control”, or “Command” on a Mac, to select more than one.")
    price = models.DecimalField(max_digits=6, decimal_places=2)
    shipping_cost = models.DecimalField(max_digits=6, decimal_places=2)
    description_short = models.TextField(max_length=100, default="", help_text="Limit 100 characters: Brief discription of the item")
    description_full = models.TextField(max_length=1000, default="", help_text="Your full item description when item details are viewed")
    product_image = models.ImageField(upload_to='product_images', help_text="There are no image size restrictions, but sqaure images will always render without any cropping.")
    date_listed = models.DateTimeField(auto_now_add=True)
    quantity = models.PositiveIntegerField(help_text="Quantity available - Default 1", default=1)
    total_purchases = models.PositiveIntegerField(default=0)

    def __str__(self):
        return self.product_name

    def save(self, **kwargs):
        slug_str = "%s" % (self.product_name) 
        unique_slugify(self, slug_str) 
        super(Product, self).save(**kwargs)


class ProductReview(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, null=True, blank=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    rating = models.PositiveIntegerField(default=5)
    subject = models.CharField(max_length=75, null=True, blank=True)
    comment = models.TextField(max_length=500, null=True, blank=True)
    timestamp = models.DateField(auto_now_add=True)

cloudland/store/forms.py
from django import forms
from .models import ProductReview

class ContactForm(forms.Form):
    your_email = forms.EmailField(required=True)
    subject = forms.CharField(required=True)
    message = forms.CharField(widget=forms.Textarea, required=True)

class ProductReviewForm(forms.ModelForm):
    class Meta:
        model = ProductReview
        fields = ['product', 'user', 'rating', 'subject', 'comment']

    def __init__(self, *args, **kwargs):
        super(ProductReviewForm, self).__init__(*args, **kwargs)
        self.fields['subject'].widget.attrs.update({
            'label': 'subject',
            'class': 'form-control',
            'placeholder': 'Add a review headline',
            'type': 'text'})
        self.fields['comment'].widget.attrs.update({
            'label': 'comment',
            'placeholder': 'What would you like others to know about this item?',
            'class': 'form-control',
            'type': 'text'})

cloudland/store/views.py
import random # to shuffle product order for display

from datetime import datetime
from django.db.models import Count
from django.conf import settings
from django.contrib.auth.models import User
from django.core.paginator import Paginator
from django.shortcuts import render, HttpResponseRedirect, reverse, redirect
from django.urls import reverse
from store.models import Product, Seller, Category, ProductReview
from carts.models import Cart, CartItem
from .forms import ContactForm, ProductReviewForm
from django.core.mail import send_mail, BadHeaderError
from django.contrib.auth.decorators import login_required

categories = Category.objects.order_by('name') # list of all categories 
sellers = Seller.objects.all().filter(is_active=True).order_by('seller_listing_name') # list of all sellers 
filterPath = ''
# list of all currently active filters
active_filters = {
    'category': 'category_All',
    'seller': 'seller_All',
    'price': 'price_default',
    'min_price': '',
    'max_price': '',
    'order_by': '?',
}
active = [] # array of active filter id's passed into template 

# sets all default filters 
def resetDefaultFilters():
    global active_filters
    active_filters = {
        'seller': 'seller_All',
        'category': 'category_All',
        'price': 'price_default',
        'min_price': '',
        'max_price': '',
        'order_by': '?',
    }
    getActiveList()
    buildFilterPath

# builds array of all currently set filters
def getActiveList():
    active.clear()
    for key in active_filters:
        if active_filters[key] != '':
            active.append(active_filters[key])

# Builds string to display the active filters in template
def buildFilterPath():
    path = ''
    category = active_filters['category']
    if 'All' in category: 
        category = 'All Categories'

    seller = active_filters['seller']
    if 'All' in seller: 
        seller = 'All Sellers'
    else:
        seller_odj = sellers.get(slug=seller)
        seller = seller_odj.seller_listing_name

    price = active_filters['price']
    if 'default' in price:
        price = 'Default $'
    else:
        num_str = price.split("_",1)[1]
        numbers = num_str.split('-')
        numbers = [int(i) for i in numbers] 
        if len(numbers) == 2:
            price = '$'+str(min(numbers))+'.00-$'+str(max(numbers))+'.00'
        if len(numbers) == 1:
            price = '$'+str(numbers[0])+'+'

    order = active_filters['order_by']
    orders = {
        '?': 'Order Default', 
        '-date_listed': 'Latest',
        'price': 'Low to High',
        '-price': 'High to Low'
    }
    for key, value in orders.items(): 
        if key == order:
            order = value

    global filterPath
    filterPath = category.title() + ' / ' + seller.title() + ' / ' + price.title() + ' / ' + order.title()

# Gets all products that match the current filters settings
def getProductsWithActiveFilters():
    # products = Product.objects.filter(quantity__gte=1).order_by('?')
    products = Product.objects.filter(seller__is_active=True).order_by('?')
    getActiveList()
    # Min and Max Price
    if active_filters['min_price'] != '' and active_filters['max_price'] != '':
        products = products.filter(price__gte=active_filters['min_price'], price__lte=active_filters['max_price'])
    # Min Price
    if active_filters['min_price'] != '' and active_filters['max_price'] == '':
        products = products.filter(price__gte=active_filters['min_price'])
    # Max Price
    if active_filters['min_price'] == '' and active_filters['max_price'] != '':
        products = products.filter(price__lte=active_filters['min_price'])
    # Seller
    if active_filters['seller'] != 'seller_All' and active_filters['seller'] != '':
        products = products.filter(seller__slug = active_filters['seller'])
    # Category
    if active_filters['category'] != 'category_All' and active_filters['category'] != '':
        products = products.filter(category__slug = active_filters['category'])
    # Order by
    if active_filters['order_by'] != '':
        products = products.order_by(active_filters['order_by'])
    
    buildFilterPath()
    return products


# Products page to view all items
def products_page_all(request):
    resetDefaultFilters()
    getParamResolver(request)
    products = getProductsWithActiveFilters()

    args = {
        'products': products,
        'active': active,
        'filterPath': filterPath
    }
    return render(request, 'store/products-page.html', args)

def products_search(request):
    words = request.GET.get('q').split(' ')
    matched = []
    for word in words:
        matched += Product.objects.filter(product_name__icontains=word)
        matched += Product.objects.filter(seller__seller_listing_name__icontains=word)
        matched += Product.objects.filter(description_full__icontains=word)
        matched += Product.objects.filter(description_short__icontains=word)
        matched += Product.objects.filter(category__name__icontains=word)
    args = {
        'products': matched,
        'active': active,
        'filterPath': 'Products matching: ' + request.GET.get('q')
    }
    return render(request, 'store/products-page.html', args)

# Filter products by selected seller
def products_by_seller(request, slug):
    getParamResolver(request)
    if slug == 'All':
        active_filters['seller'] = 'seller_All'
    else:
        active_filters['seller'] = slug
    products = getProductsWithActiveFilters()
    args = {
        'products': products,
        'active': active,
        'filterPath': filterPath
    }
    return render(request, 'store/products-page.html', args)

# Filter products by selected category
def products_by_category(request, slug):
    getParamResolver(request)
    if slug == 'All':
        active_filters['category'] = 'category_All'
    else:
        active_filters['category'] = slug
    products = getProductsWithActiveFilters()
    args = {
        'products': products,
        'active': active,
        'filterPath': filterPath
    }
    return render(request, 'store/products-page.html', args)


def getParamResolver(request):
    global active_filters
    # Price GET params
    min_price = request.GET.get('min_price')
    max_price = request.GET.get('max_price')
    price_default = request.GET.get('price')
    if price_default:
        active_filters['price'] = 'price_default'
    else:
        if min_price and not max_price:
            if min_price.isnumeric():
                active_filters['price'] = 'price_'+str(min_price)
                active_filters['min_price'] = min_price
        elif min_price and max_price:
            if min_price.isnumeric() and max_price.isnumeric():
                active_filters['price'] = 'price_'+str(min_price)+'-'+str(max_price)
                active_filters['min_price'] = min_price
                active_filters['max_price'] = max_price
            else:
                pass

    # order_by GET param
    valid_orders = ['?', '-date_listed', 'price', '-price']
    order_by = request.GET.get('order_by')
    if order_by in valid_orders:
        active_filters['order_by'] = order_by

    return

# View when an item is selected to display item detail
def view_item(request, slug):
    if request.method == 'POST':
        form = ProductReviewForm(request.POST)
        if form.is_valid():
            form = form.save(commit=False)
            form.product = Product.objects.get(slug=slug)
            form.user = request.user
            form.rating = request.POST.get('rating')
            form.save()
        else:
            print(form.errors)
        return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

    form = ProductReviewForm()
    product = Product.objects.get(slug=slug)
    reviews = ProductReview.objects.filter(product = product)
    n = range(5)
    qaunt_available = range(1, product.quantity+1)

    total_carts_count = product.cartitem_set.filter(cart__active=True).count()
    if total_carts_count == 0:
        args = {
            'product': product,
            'qaunt_available': qaunt_available,
            'reviews': reviews,
            'n': n,
            'form': form,
        }
    elif total_carts_count == 1:
        total_carts_count = str(total_carts_count) + ' person has this item in their cart'
        args = {
            'product': product,
            'qaunt_available': qaunt_available,
            'total_carts_count': total_carts_count,
            'reviews': reviews,
            'n': n,
            'form': form,
        }
    else:
        total_carts_count = str(total_carts_count) + ' people have this item in their cart'
        args = {
            'product': product,
            'qaunt_available': qaunt_available,
            'total_carts_count': total_carts_count,
            'reviews': reviews,
            'n': n,
            'form': form,
        }

    return render(request, 'store/view-item.html', args)

def post_review(request, id):
    if request.method == 'POST':
        product = Product.objects.get(product_id=id)
        user = request.user
        form = ProductReviewForm(request.POST)
        if form.is_valid():
            form = form.save(commit=False)
            form.product = product
            form.user = user
            print('VALID')
            print(new_review) 
            new_review.save()
        else:
            print(form.errors)
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

# About page
def about(request):
    return render(request, 'store/about.html', {'sellers': sellers})

# Contact page
@login_required
def contact(request):
    if request.method == 'GET':
        form = ContactForm()
    else:
        form = ContactForm(request.POST)
        if form.is_valid():
            from_email = form.cleaned_data['your_email']
            subject = "Message from: " + from_email + " re: " + form.cleaned_data['subject']
            message = form.cleaned_data['message']

cloudland/store/templates/store/about.html
<!-- Extends base template  -->
{% extends "store/base.html" %}
<!-- Loads static content to access content in static directory -->
{% load static %}
<!-- Page title for window tab -->
{% block page %}About{% endblock page%}
<!-- Custom page styles -->
{% block styles %}
<link href="{% static 'store/css/about-styles.css' %}" rel="stylesheet">{% endblock styles %}
<!-- fills content block in base template -->
{% block content %}
<header class="text-center my-4">
    <div class="container">
        <h2>Meet the Team</h2>
    </div>
</header>
<div class="container" style="min-height: 100vh;">
    <hr>


    <div class="card-columns">
        {% for seller in sellers %}
        <div class="card border-0 mb-2">
            <img class="card-img-top" src="{{ seller.profile_picture.url }}" alt="{{ seller.seller_listing_name }} Profile Picture">
            <div class="card-body text-left">
                <div class="text-center">
                    <h3 class="card-title mb-0">{{ seller.seller_full_name }}</h3>
                    <h5 class="card-text text-secondary">// {{ seller.seller_listing_name }} //</h5>
                    <h5 class="card-text text-black-50"><i class="fas fa-envelope fa-xs"></i> {{ seller.email }}</h5>
                </div>
                <p class="p-2">{{ seller.bio_description }}</p>
            </div>
        </div>
        {% endfor %}
        <div class="card border-0 mb-2">
            <img class="card-img-top" src="{% static 'store/media/brand/michaelpermyashkin_profile.jpg' %}" alt="Michael Permyashkin Profile Picture">
            <div class="card-body text-center">
                <div class="card-body text-left">
                    <div class="text-center">
                        <h3 class="card-title mb-0">Michael Permyashkin</h3>
                        <h5 class="card-text text-secondary">// Designer and Developer //</h5>
                        <h5 class="card-text text-black-50"><i class="fas fa-envelope fa-xs"></i> michael.permyashkin@gmail.com</h5>
                    </div>
                    <p class="p-2 text-left">
                        I was born and raised in a small college town in central Pennsylvania called Lewisburg, the home of Bucknell University. I am the 8th of 13 children to parents who emmagrated from the Soviet Union. I am a senior at Shippensburg studying software engineering.
                        I like to write code that works well and looks pretty. I write music, read books and worship Jesus.
                    </p>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

cloudland/store/templates/store/view-item.html
<!-- Extends base template  -->
{% extends "store/base.html" %}
<!-- Crispy forms for styling -->
{% load crispy_forms_tags %}
<!-- Loads static content to access content in static directory -->
{% load static %}
<!-- Page title for window tab -->
{% block page %}Shop{% endblock page%}
<!-- Custom page styles -->
{% block styles %}
<link href="{% static 'store/css/view-item-styles.css' %}" rel="stylesheet">{% endblock styles %}
<!-- fills content block in base template -->
{% block content %}
<div class="container" style="min-height: 100vh;">
    <h1 class="my-2">{{ product.product_name }} <small class="text-muted" style="font-size: 0.5em;"> by {{ product.seller.seller_listing_name }} </small></h1>
    <div class="row">
        <div class="col-md-7" id="image-container">
            <div class="img-container">
                <img src="{{ product.product_image.url }}" alt="Product image">
                <div class="overlay" id="enlarge">
                    <span><h3>Click to enlarge</h3></span>
                </div>
            </div>
            <!-- Creates the bootstrap modal where the image will appear -->
            <div class="modal fade" id="imagemodal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                <div class="modal-dialog modal-dialog-centered modal-lg">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h4 class="modal-title" id="myModalLabel">{{ product.product_name }} Preview</h4>
                            <button type="button" class="close" data-dismiss="modal"><i class="fas fa-times" aria-hidden="true"></i><span class="sr-only">Close</span></button>
                        </div>
                        <div class="modal-body">
                            <img src="{{ product.product_image.url }}" id="imagepreview">
                        </div>
                    </div>
                </div>
            </div>
            <script>
                $("#enlarge").on("click", function() {
                    $('#imagemodal').modal('show'); // imagemodal is the id attribute assigned to the bootstrap modal, then i use the show function
                });
            </script>
        </div>
        <div class="col-md-5">
            <h1><b>${{ product.price }}</b><small class="text-muted" style="font-size: 0.5em;"> + shipping</small></h1>
            <h3 class="mt-3">Description</h3>
            <p class="mt-1 mb-5">{{ product.description_short }}</p>

            <!-- If qauntity == 5 change from plural -->
            {% if product.quantity > 5%}
            <h4 class="text-success">{{ product.quantity }} Items Remaining</h4>
            <h6 class="text-danger">{{total_carts_count}}</h6>
            {% else %}
            <!-- If qauntity == 1 change from plural -->
            {% if product.quantity == 1 %}
            <h4 class="text-danger">{{ product.quantity }} Item Remaining</h4>
            <h6 class="text-danger">{{total_carts_count}}</h6>
            {% else %}

            <!-- If Quantity == 0 -->
            {% if product.quantity == 0 %}
            <h4 class="text-danger">Out of Stock</h4>
            {% else %}
            <h4 class="text-danger">{{ product.quantity }} Items Remaining</h4>
            <h6 class="text-danger">{{total_carts_count}}</h6>
            <!-- ./end nested if -->
            {% endif %}
            <!-- ./end nested if -->
            {% endif %}
            <!-- ./end if -->
            {% endif %}

            <!-- If in stock show cart and quantity selection -->
            {% if product.quantity != 0 %}
            <div class="row">
                <div class="col-4">
                    <dl class="param param-inline">
                        <dt>Quantity: </dt>
                        <dd>
                            <select class="form-control form-control-sm rounded-0" onChange="getSelectedQuantity(this);">
                            {% for i in qaunt_available %} 
                            <option value='{{ i }}'> {{ i }} </option>
                            {% endfor %}
                            </select>
                        </dd>
                    </dl>
                </div>
                <div class="col-8">
                    <div>
                        {% if user.groups.all.0.name == 'Seller' %}
                        <!-- If seller -->
                        <button class="btn border-0 rounded-0 mt-4 disabled" id="btn-add-to-cart">
                            ADD TO CART
                        </button>
                        <!-- If not seller -->
                        {% else %}
                        <!-- Form to add product to cart -->
                        <form method="post" action="{% url 'add_to_cart' product.product_id %}">
                            {% csrf_token %}
                            <input type="hidden" id="selected_quantity" name="selected_quantity" value="1">
                            <button type="submit" class="btn border-0 rounded-0 mt-4" id="btn-add-to-cart">
                                ADD TO CART
                            </button>
                        </form>
                        <!-- ./endif -->
                        {% endif %}
                    </div>
                </div>
            </div>
            {% else %}
            <div class="row">
                <div class="col-4">
                    <dl class="param param-inline">
                        <dt>Quantity: </dt>
                        <dd>
                            <select class="form-control form-control-sm rounded-0">
                                <option value='0'> 0 </option>
                            </select>
                        </dd>
                    </dl>
                </div>
                <div class="col-8">
                    <button type="submit" class="btn border-0 rounded-0 mt-4 disabled" id="btn-add-to-cart" id="hidden-button">ADD TO CART</button>
                </div>
            </div>
            {% endif %}
        </div>
    </div>

    <div class="col-md-12 ml-0 pl-0">
        <h1>Details</h1>
        <p>{{ product.description_full }}</p>
        <br>
        <h1>Shipping</h1>
        <div class="col-md-10 ml-0 pl-0">
            <table class="table table-borderless ">
                <thead class="thead-light">
                    <tr>
                        <th scope="col">Type</th>
                        <th scope="col">Estimated Delivery</th>
                        <th scope="col">Product Shipping</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td scope="row">Standard Ground</td>
                        <td>5-10 business days</td>
                        <td>${{ product.shipping_cost }}</td>
                    </tr>
                </tbody>
            </table>
        </div>
        <small>
            **Sellers ship products individually. Products in a single order will arrive seperately and shipping time may vary.
        </small>
        <br>
        <h1 class="mt-5">Reviews</h1>
        <div class="col-md-12 ml-0 pl-0">
            {% for review in reviews %}
            <div class="card p-3 rounded-0" id="{{review.id}}">
                <div class="card-body">
                    <h4 class="card-title"><b>{{ review.subject }}</b></h4>
                    <div class="star-container">
                        {% for i in n %}
                        <!-- star loop -->
                        {% if i >= review.rating %}
                        <span class="fa fa-star empty"></span>
                        <!-- ./ star loop -->
                        {% else %}
                        <span class="fa fa-star filled"></span> {% endif %} {% endfor %}
                    </div>
                    <hr>
                    <p class="card-text">{{ review.comment }}</p>
                    <h6 class="card-subtitle mb-2 text-muted">Posted by {{ review.user.username }} on {{ review.timestamp }}</h6>
                </div>
            </div>
            {% endfor %}
            <div class="text-center mt-3">
                <div class="btn btn-dark" id="toggle-review-show">Add a Review</div>
            </div>
        </div>
    </div>
    <br>
    <div class="col-md-10 m-auto" id='review-form' style="display: none;">
        <!-- <form action="{% url 'post-review' product.product_id %}" method="post"> -->
        <form action="" method="post">
            {% csrf_token %}
            <!-- Rating Stars Box -->
            <section class='rating-widget'>
                <input type="hidden" name="rating" min="0" class="numberinput form-control" required="" id="id_rating">
                <div id="div_id_rating" class="form-group">
                    <label for="id_rating" class="">Star Rating</label>
                    <!-- Rating Stars Box -->
                    <div class='rating-stars form-group'>
                        <ul id='stars'>
                            <li class='star' title='Poor' data-value='1'>
                                <i class='fa fa-star fa-fw'></i>
                            </li>
                            <li class='star' title='Fair' data-value='2'>
                                <i class='fa fa-star fa-fw'></i>
                            </li>
                            <li class='star' title='Good' data-value='3'>
                                <i class='fa fa-star fa-fw'></i>
                            </li>
                            <li class='star' title='Excellent' data-value='4'>
                                <i class='fa fa-star fa-fw'></i>
                            </li>
                            <li class='star' title='WOW!!!' data-value='5'>
                                <i class='fa fa-star fa-fw'></i>
                            </li>
                        </ul>
                    </div>
                </div>
            </section>
            {{ form.subject|as_crispy_field }} {{ form.comment|as_crispy_field }}
            <div class="row" id="review-form-options">
                <div class="col-6">
                    <div class="btn btn-warning" id="cancel-review">Cancel</div>
                </div>
                <div class="col-6">
                    <button type="submit" class="btn btn-success" id="post-review">Post</button>
                </div>
            </div>
        </form>
    </div>
</div>
<script>
    function getSelectedQuantity(sel) {
        document.getElementById("selected_quantity").value = sel.options[sel.selectedIndex].value;
    }
    $(document).ready(function() {
        /* 1. Visualizing things on Hover - See next part for action on click */
        $('#stars li').on('mouseover', function() {
            var onStar = parseInt($(this).data('value'), 10); // The star currently mouse on

            // Now highlight all the stars that's not after the current hovered star
            $(this).parent().children('li.star').each(function(e) {
                if (e < onStar) {
                    $(this).addClass('hover');
                } else {
                    $(this).removeClass('hover');
                }
            });

        }).on('mouseout', function() {
            $(this).parent().children('li.star').each(function(e) {
                $(this).removeClass('hover');
            });
        });


        /* 2. Action to perform on click */
        $('#stars li').on('click', function() {
            var onStar = parseInt($(this).data('value'), 10); // The star currently selected
            var stars = $(this).parent().children('li.star');

            for (i = 0; i < stars.length; i++) {
                $(stars[i]).removeClass('selected');
            }

            for (i = 0; i < onStar; i++) {
                $(stars[i]).addClass('selected');
            }

            var ratingValue = parseInt($('#stars li.selected').last().data('value'), 10);
            hidden_val = $('#id_rating').val(ratingValue);
            var msg = "";
            if (ratingValue > 1) {
                msg = "Thanks! You rated this " + ratingValue + " stars.";
            } else {
                msg = "We will improve ourselves. You rated this " + ratingValue + " stars.";
            }
            responseMessage(msg);
        });
    });

    function responseMessage(msg) {
        $('.success-box').fadeIn(200);
        $('.success-box div.text-message').html("<span>" + msg + "</span>");
    }

    // Show review form
    $('#toggle-review-show').click(function() {
        $('#review-form').fadeIn(500);
        $(this).hide();
    });

    // Hide review form
    $('#cancel-review').click(function() {
        $('#review-form').hide();
        $('#toggle-review-show').show();
    });
</script>
{% endblock content %}