cloudland/accounts/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('register/', views.register_request, name='accounts-register'),
    path('login/', views.login_request, name='accounts-login'),
    path("logout", views.logout_request, name="accounts-logout"),
    path("reset-password/", views.password_reset, name="accounts-password-reset"),
    path('dashboard/', views.dashboard, name='accounts-dashboard'),
    path('activate/<str:activation_key>', views.email_activation, name='activation-view')
]

cloudland/carts/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.cart, name='store-cart'),
    path('add/id=<int:id>', views.add_to_cart, name='add_to_cart'),
    path('remove/id=<int:id>', views.remove_from_cart, name='remove_from_cart'),
]

cloudland/cloudland/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("django.contrib.auth.urls")), # build in django auth urls
    path('', include('store.urls')),
    path('accounts/', include('accounts.urls')),
    path('cart/', include('carts.urls')),
    path('orders/', include('orders.urls')),
    path('sellers/', include('sellers.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cloudland/accounts/models.py
from django.db import models
from django.conf import settings
from django.contrib.auth.models import User
from django.core.mail import send_mail
from django.urls import reverse

from django.template.loader import render_to_string

from localflavor.us.us_states import US_STATES

class UserDefaultAddresses(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    shipping = models.ForeignKey("UserAddress", null=True, blank=True, on_delete=models.CASCADE)
    billing = models.ForeignKey("UserBillingAddress", null=True, blank=True, on_delete=models.CASCADE)

    def __str__(self):
        return str(self.user.username)
    

class UserAddress(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    first_name = models.CharField(max_length=120)
    last_name = models.CharField(max_length=120)
    address = models.CharField(max_length=120)
    address2 = models.CharField(max_length=120, null=True, blank=True)
    city = models.CharField(max_length=120)
    state = models.CharField(max_length=120, choices=US_STATES)
    zipcode = models.CharField(max_length=120)
    shipping = models.BooleanField(default=True)
    timestamp = models.DateTimeField(auto_now=True, auto_now_add=False)
    updated = models.DateTimeField(auto_now=False, auto_now_add=True)

    class Meta:
        ordering = ['-updated', '-timestamp']

    def __str__(self):
        return self.get_address()

    def get_address(self):
        if self.address2:
            return '%s, %s, %s, %s, %s' % (self.address, self.address2, self.city, self.state, self.zipcode)
        else:
            return '%s, %s, %s, %s' % (self.address, self.city, self.state, self.zipcode)


class UserBillingAddress(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    first_name = models.CharField(max_length=120)
    last_name = models.CharField(max_length=120)
    address = models.CharField(max_length=120)
    address2 = models.CharField(max_length=120, null=True, blank=True)
    city = models.CharField(max_length=120)
    state = models.CharField(max_length=120, choices=US_STATES)
    zipcode = models.CharField(max_length=120)
    timestamp = models.DateTimeField(auto_now=True, auto_now_add=False)
    updated = models.DateTimeField(auto_now=False, auto_now_add=True)
    
    class Meta:
        ordering = ['-updated', '-timestamp']

    def __str__(self):
        return self.get_address()

    def get_address(self):
        if self.address2:
            return '%s, %s, %s, %s, %s' % (self.address, self.address2, self.city, self.state, self.zipcode)
        else:
            return '%s, %s, %s, %s' % (self.address, self.city, self.state, self.zipcode)



class UserStripe(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    stripe_id = models.CharField(max_length=120, null=True, blank=True)

    def __str__(self):
        return str(self.stripe_id)


class EmailConfirmed(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    activation_key = models.CharField(max_length=200)
    confirmed = models.BooleanField(default=False)

    class Meta:
        verbose_name_plural = "Email Confirmations"

    def __str__(self):
        return str(self.confirmed)

    def activate_user_email(self):
        subject = 'Activate your Email'
        activation_url = '%s%s' %(settings.SITE_URL, reverse('activation-view', args=[self.activation_key]))
        context = {
            'user_firstname': self.user.first_name,
            'activation_key': self.activation_key,
            'activation_url': activation_url,
        }
        message = render_to_string('accounts/activation_message.txt', context)
        from_email = settings.DEFAULT_FROM_EMAIL
        self.email_user(subject, message, from_email)

    def email_user(self, subject, message, from_email=None, **kwargs):
        send_mail(subject, message, from_email, [self.user.email], kwargs)

cloudland/carts/models.py
from django.db import models
from store.models import Product


class CartItem(models.Model):
    cart = models.ForeignKey('Cart', on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=0)
    line_total = models.DecimalField(default=0.00, max_digits=5, decimal_places=2)

    def __str__(self):
        return self.product.product_name


class Cart(models.Model):
    sub_total = models.DecimalField(max_digits=5, decimal_places=2, default=0.00)
    shipping = models.DecimalField(max_digits=5, decimal_places=2, default=0.00)
    grand_total = models.DecimalField(max_digits=7, decimal_places=2, default=0.00)
    timestamp = models.DateTimeField(auto_now_add=True, auto_now=False)
    updated = models.DateTimeField(auto_now_add=False, auto_now=True)
    active = models.BooleanField(default=True)

cloudland/orders/models.py
from django.db import models
from carts.models import Cart
from django.conf import settings
from accounts.models import UserAddress, UserBillingAddress

STATUS_CHOICES = (
    ('Started', 'Started'),
    ('Abandoned', 'Abandoned'),
    ('Complete', 'Complete'),
)

class Order(models.Model):
    order_id = models.CharField(max_length=120, default='ABC', unique=True)
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    status = models.CharField(max_length=120, choices=STATUS_CHOICES, default='Started')
    user = models.ForeignKey(settings.AUTH_USER_MODEL, blank=True, null=True, on_delete=models.CASCADE)
    shipping_address = models.ForeignKey(UserAddress, on_delete=models.CASCADE, blank=True, null=True)
    billing_address = models.ForeignKey(UserBillingAddress, on_delete=models.CASCADE, blank=True, null=True)
    sub_total = models.DecimalField(default=0.00, max_digits=5, decimal_places=2)
    shipping = models.DecimalField(default=0.00, max_digits=5, decimal_places=2)
    order_tax = models.DecimalField(default=0.00, max_digits=5, decimal_places=2)
    order_total = models.DecimalField(default=0.00, max_digits=5, decimal_places=2)
    order_receipt_link = models.CharField(max_length=240, null=True, blank=True)
    timestamp_created = models.DateTimeField(auto_now_add=True, auto_now=False)
    timestamp_completed = models.DateTimeField(auto_now_add=False, auto_now=True)

    def __str__(self):
        return self.order_id

    def get_order_date(self):
        if self.address2:
            return '%s, %s, %s, %s, %s' % (self.address, self.address2, self.city, self.state, self.zipcode)
        else:
            return '%s, %s, %s, %s' % (self.address, self.city, self.state, self.zipcode)

cloudland/accounts/views.py
import re
from django.shortcuts import render, redirect, Http404, HttpResponseRedirect
from django.contrib import messages
from django.contrib.auth import login as auth_login
from django.contrib.auth import authenticate, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.urls import reverse
from carts.models import Cart
import store.urls 
from .forms import RegisterForm, UsersLoginForm, UserAddressForm, UserBillingAddressForm, UserPasswordResetForm
from .models import EmailConfirmed, UserDefaultAddresses

from django.conf import settings

# Customer Dashboard
@login_required
def dashboard(request):
    try:
        cartID = request.session['cart_id'] 
        cart = Cart.objects.get(id=cartID)
    except:
        cartID = None

    if cartID != None:
        cart = Cart.objects.get(id=cartID) 
        args = {
            'cart': cart,
        }
        return render(request, 'accounts/dashboard.html', args)
    else:
        return render(request, 'accounts/dashboard.html')


# Signup
def register_request(request):
    #  create new user
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            auth_login(request, user)
            messages.success(request, "Registration Successful! Please confirm your email now.")
            next_url = request.GET.get('next')
            if next_url:
                return redirect(next_url)
            else:
                return redirect('/')
    # else they need to register
    else:
        form = RegisterForm()
    return render(request, 'accounts/register.html', {'form': form})

# Login
def login_request(request):
    # Authenticate user login attempt
    if request.method == 'POST':
        form = UsersLoginForm(request.POST or None)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username = username, password = password)
            if user.groups.filter(name='Seller').count():
                messages.warning(request, "Your account has seller permissions, please log in here. If this is a mistake please contact us at cloudlandonline@gmail.com")
                return redirect(reverse('seller-login'))
            else:
                auth_login(request, user)
                next_url = request.GET.get('next')
                if next_url:
                    return redirect(next_url)
                else:
                    return redirect('/')
    # else render login page
    else:
        form = UsersLoginForm()
    return render(request, 'accounts/login.html', {'form': form})

# Login
def password_reset(request):
    # Authenticate user login attempt
    if request.method == 'POST':
        form = UserPasswordResetForm(request.POST or None)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            email = form.cleaned_data.get('email')
            password = form.cleaned_data.get('password')
            user = User.objects.get(username=username, email=email)
            print(user)
            user.set_password(password)
            user.save()
            return redirect(reverse('accounts-login'))
    # else render login page
    else:
        form = UserPasswordResetForm()
    return render(request, 'accounts/reset-password.html', {'form': form})

def logout_request(request):
    logout(request)
    return redirect(reverse('accounts-login'))


SHA1_RE = re.compile('^[a-f0-9]{40}$')
# Email activation view
def email_activation(request, activation_key):
    # Check if key is valid
    if SHA1_RE.search(activation_key):
        try:
            instance = EmailConfirmed.objects.get(activation_key=activation_key)
        except EmailConfirmed.DoesNotExist:
            instance = None
            raise Http404
        # Confirm the email
        if instance is not None and not instance.confirmed:
            page_message = 'Thank you! Your email has been confirmed!'
            context = {'page_message': page_message}
            instance.confirmed = True
            instance.activation_key = 'Confirmed'
            instance.save()
        # This email is already marked as being confirmed
        elif instance is not None and instance.confirmed:
            page_message = 'Your email has already been confirmed'
            context = {'page_message': page_message}
        else:
            page_message = None
            context = {}

        return render(request, 'accounts/activation-complete.html', context)
    # Raise 404 if invalid key
    else: 
        raise Http404


def add_user_address(request):
    try:
        redirect_view = request.GET['next']
    except:
        redirect_view = None

    if request.method == 'POST':
        form = UserAddressForm(request.POST)
        if form.is_valid():
            new_address = form.save(commit=False)
            new_address.user = request.user
            new_address.save()
            is_default = form['default']
            if is_default:
                default_address, created = UserDefaultAddresses.objects.get_or_create(user=request.user)
                default_address.shipping = new_address
                default_address.save()
            if redirect_view != None:
                return HttpResponseRedirect(reverse(str(redirect_view))+'?shipping-added') # add+=True if address from form was saved 
    else:
        raise Http404

def add_user_billing_address(request):
    try:
        redirect_view = request.GET['next']
    except:
        redirect_view = None

    if request.method == 'POST':
        form = UserBillingAddressForm(request.POST)
        if form.is_valid():
            new_address = form.save(commit=False)
            new_address.user = request.user
            new_address.save()
            is_default = form['default']
            if is_default:
                default_address, created = UserDefaultAddresses.objects.get_or_create(user=request.user)
                default_address.billing = new_address
                default_address.save()
            if redirect_view != None:
                return HttpResponseRedirect(reverse(str(redirect_view))+'?billing-added') # add+=True if address from form was saved 
    else:
        raise Http404

cloudland/accounts/templates/accounts/activation-complete.html
<!-- Extends base template  -->
{% extends "store/base.html" %}
<!-- Loads static content to access content in static directory -->
{% load static %}
<!-- Crispy forms for styling -->
{% load crispy_forms_tags %}
<!-- Page title for window tab -->
{% block page %}Account{% endblock page%}
<!-- Custom page styles -->
{% block styles %}
<link href="{% static 'accounts/css/activation-complete-styles.css' %}" rel="stylesheet"> {% endblock styles %}
<!-- fills content block in base template -->
{% block content %}
<div class="container text-center" style="height: 100vh;">
    {% if page_message %}
    <h1 class="mt-5 pt-5">{{ page_message }}</h1>
    {% else %}
    <h1 class="mt-5 pt-5">Oops, looks like something went wrong with your email activation</h1>
    {% endif %}
    <a href="{% url 'store-products-page-all-home' %} " id="btn-continue-shopping" class="btn border-0 rounded-0 justify-content-start mt-3">Start Shopping</a>
</div>
{% endblock content %}

cloudland/accounts/templates/accounts/dashboard.html
<!-- Extends base template  -->
{% extends "store/base.html" %}
<!-- Loads static content to access content in static directory -->
{% load static %}
<!-- Page title for window tab -->
{% block page %}Dashboard{% endblock page%}
<!-- Custom style sheet -->
{% block styles %}
<link href="{% static 'accounts/css/dashboard-styles.css' %}" rel="stylesheet"> {% endblock styles %}
<!-- fills content block in base template -->
{% block content %}
<div class="container" style="min-height: 100vh;">
    <div class="my-4 text-center">
        <h2>My Account</h2>
    </div>
    <hr>
    <div class="row justify-content-center">
        <div class="col-md-4 order-md-2 mb-4">
            <h4 class="d-flex justify-content-between align-items-center mb-3">
                <span class="text-muted">My cart</span>
                <span class="badge badge-success badge-pill">{{cart.cartitem_set.all|length}}</span>
            </h4>
            <ul class="list-group mb-3 rounded-0">
                {% if cart.cartitem_set.all|length != 0 %} {% for item in cart.cartitem_set.all %}
                <li class="list-group-item d-flex justify-content-between lh-condensed">
                    <div>
                        <h6 class="my-0">{{ item.product.product_name }} x {{ item.quantity }}</h6>
                        <small class="text-muted">{{ item.product.description_short }}</small>
                    </div>
                    <span class="text-muted">${{ item.line_total }}</span>
                </li>
                {% endfor %}
                <div id="totals">
                    <li class="list-group-item">
                        <div class="d-flex justify-content-between">
                            <span>Subtotal</span>
                            <h6 class="mt-1"><b>$ {{ cart.sub_total }}</b></h6>
                        </div>
                        <div class="d-flex justify-content-between">
                            <span>Shipping</span>
                            <h6 class="mt-1"><b>$ {{ cart.shipping }}</b></h6>
                        </div>
                        <hr>
                        <div class="d-flex justify-content-between text-success">
                            <span>Total (USD)</span>
                            <h4><b>$ {{ cart.grand_total }}</b></h4>
                        </div>
                    </li>
                </div>
                {% else %}
                <li class="list-group-item d-flex justify-content-between lh-condensed">
                    <h3 class="text-muted">Empty Cart</h3>
                </li>
                {% endif%}
            </ul>
        </div>
        <div class="col-md-7 order-md-1">
            <h3 class="text-center">My Orders</h3>
            <!-- If orders exists then display -->
            {% if user.order_set.all|length != 0 %}
            <!-- Show order cards for user -->
            {% for order in user.order_set.all reversed %}
            <!-- Only show completed orders here -->
            {% if order.status == 'Complete' %}
            <div class="card rounded-0 my-4">
                <div class="card-header bg-dark text-white">
                    <h5>Order #: {{ order.order_id }}</h5>
                </div>
                <div class="card-body p-2">
                    <h4 class="ml-1">Items</h4>
                    <div class="col-12">
                        {% for item in order.cart.cartitem_set.all %}
                        <li class="list-group-item d-flex justify-content-between lh-condensed">
                            <div>
                                <h6 class="my-0">{{ item.product.product_name }} x {{ item.quantity }}</h6>
                                <small class="text-muted">{{ item.product.description_short }}</small>
                            </div>
                            <span class="text-muted">${{ item.line_total }}</span>
                        </li>
                        {% endfor %}
                    </div>
                    <h4 class="ml-1 mt-2">Details</h4>
                    <div class="col-12">
                        <h6><b>Order Date:</b> {{ order.timestamp_completed }}</h6>
                        <h6><a href="{{ order.order_receipt_link }}" target="_blank">View your receipt here</a></h6>
                    </div>
                </div>
                <div class="card-footer bg-light">
                    <h6>Subtotal: {{ order.sub_total }}</h6>
                    <h6>Shipping: {{ order.shipping }}</h6>
                    <h5 class="text-success">Total $: {{ order.order_total }}</h5>
                </div>
            </div>
            {% endif %}
            <!-- ./ end only complete orders -->
            {% endfor %}
            <!-- No orders to display -->
            {% else %}
            <h3 class="text-center mt-4 mx-5">Oops, you haven't made any orders yet. When you do, you'll be able to see them here!</h3>
            {% endif %}
        </div>
    </div>
    <div class="text-right">
        <a href="{% url 'accounts-logout' %}" class="btn btn-danger mt-5 rounded-0">Logout</a>
    </div>
</div>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script>
    $(document).ready(function() {
        // Add smooth scrolling to all links
        $("a").on('click', function(event) {

            // Make sure this.hash has a value before overriding default behavior
            if (this.hash !== "") {
                // Prevent default anchor click behavior
                event.preventDefault();

                // Store hash
                var hash = this.hash;

                // Using jQuery's animate() method to add smooth page scroll
                // The optional number (800) specifies the number of milliseconds it takes to scroll to the specified area
                $('html, body').animate({
                    scrollTop: $(hash).offset().top
                }, 500, function() {

                    // Add hash (#) to URL when done scrolling (default click behavior)
                    window.location.hash = hash;
                });
            } // End if
        });
    });
</script>
{% endblock content %}

cloudland/accounts/templates/accounts/login.html
<!-- Extends base template  -->
{% extends "store/base.html" %}
<!-- Loads static content to access content in static directory -->
{% load static %}
<!-- Crispy forms for styling -->
{% load crispy_forms_tags %}
<!-- Page title for window tab -->
{% block page %}Account{% endblock page%}
<!-- Custom page styles -->
{% block styles %}
<link href="{% static 'accounts/css/login-register-styles.css' %}" rel="stylesheet"> {% endblock styles %}
<!-- fills content block in base template -->
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-lg-10 mx-auto">
            <div class="card card-signin flex-row my-5 rounded-0 border-0 p-5">
                <div class="card-body border-0">
                    <h5 class="card-title text-center">SIGN IN</h5>
                    <form class="form-signin" method="POST">
                        {% csrf_token %} {{ form | crispy }}
                        <button class="btn btn-primary btn-block" type="submit">Login</button>
                        <a class="d-block text-center mt-2" href="{% url 'accounts-register' %}">Register</a>
                        <hr class="my-4">
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

cloudland/accounts/templates/accounts/register.html
<!-- Extends base template  -->
{% extends "store/base.html" %}
<!-- Loads static content to access content in static directory -->
{% load static %}
<!-- Crispy forms for styling -->
{% load crispy_forms_tags %}
<!-- Page title for window tab -->
{% block page %}Account{% endblock page%}
<!-- Custom page styles -->
{% block styles %}
<link href="{% static 'accounts/css/login-register-styles.css' %}" rel="stylesheet"> {% endblock styles %}
<!-- fills content block in base template -->
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-lg-10 mx-auto">
            <div class="card card-signin flex-row my-5 rounded-0 border-0 p-5">
                <div class="card-body border-0">
                    <h5 class="card-title text-center">SIGN UP</h5>
                    <form class="form-signin" method="POST">
                        {% csrf_token %} {{ form|crispy }}
                        <button class="btn btn-lg btn-primary btn-block" type="submit">Register</button>
                        <a class="d-block text-center mt-2" href="{% url 'accounts-login' %}">Sign In</a>
                        <a class="d-block text-center" href="{% url 'accounts-password-reset' %}">Forgot password?</a>
                        <a class="d-block text-center mt-3" href="{% url 'seller-login' %}">I'm a Seller</a>
                        <hr class="my-4">
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

cloudland/accounts/templates/accounts/reset-password.html
<!-- Extends base template  -->
{% extends "store/base.html" %}
<!-- Loads static content to access content in static directory -->
{% load static %}
<!-- Crispy forms for styling -->
{% load crispy_forms_tags %}
<!-- Page title for window tab -->
{% block page %}Account{% endblock page%}
<!-- Custom page styles -->
{% block styles %}
<link href="{% static 'accounts/css/login-register-styles.css' %}" rel="stylesheet"> {% endblock styles %}
<!-- fills content block in base template -->
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-lg-10 mx-auto">
            <div class="card card-signin flex-row my-5 rounded-0 border-0 p-5">
                <div class="card-body border-0">
                    <h5 class="card-title text-center">PASSWORD RESET</h5>
                    <form class="form-signin" method="POST">
                        {% csrf_token %} {{ form | crispy }}
                        <button class="btn btn-primary btn-block" type="submit">Reset Password</button>
                        <a class="d-block text-center mt-2" href="{% url 'accounts-login' %}">Login</a>
                        <a class="d-block text-center" href="{% url 'accounts-register' %}">Register</a>
                        <a class="d-block text-center mt-3" href="{% url 'seller-login' %}">I'm a Seller</a>
                        <hr class="my-4">
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}