cloudland/carts/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.cart, name='store-cart'),
    path('add/id=<int:id>', views.add_to_cart, name='add_to_cart'),
    path('remove/id=<int:id>', views.remove_from_cart, name='remove_from_cart'),
]

cloudland/cloudland/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("django.contrib.auth.urls")), # build in django auth urls
    path('', include('store.urls')),
    path('accounts/', include('accounts.urls')),
    path('cart/', include('carts.urls')),
    path('orders/', include('orders.urls')),
    path('sellers/', include('sellers.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cloudland/sellers/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('dasboard', views.seller_dashboard, name='seller-dashboard'),
    path('add-product/', views.add_product, name='add-product'),
    path('delete-product/pid=<int:id>', views.delete_product, name='delete-product'),
    path('edit/<slug:slug>', views.edit_product, name='edit-product'),
    path('edit/s/<slug:slug>', views.edit_bio, name='edit-bio'),
    path('login/', views.seller_login, name='seller-login'),
]

cloudland/carts/models.py
from django.db import models
from store.models import Product


class CartItem(models.Model):
    cart = models.ForeignKey('Cart', on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=0)
    line_total = models.DecimalField(default=0.00, max_digits=5, decimal_places=2)

    def __str__(self):
        return self.product.product_name


class Cart(models.Model):
    sub_total = models.DecimalField(max_digits=5, decimal_places=2, default=0.00)
    shipping = models.DecimalField(max_digits=5, decimal_places=2, default=0.00)
    grand_total = models.DecimalField(max_digits=7, decimal_places=2, default=0.00)
    timestamp = models.DateTimeField(auto_now_add=True, auto_now=False)
    updated = models.DateTimeField(auto_now_add=False, auto_now=True)
    active = models.BooleanField(default=True)

cloudland/sellers/models.py
from django.db import models

# Create your models here.

cloudland/store/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.utils.datetime_safe import datetime

from .utils import unique_slugify

class Seller(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True)
    profile_picture = models.ImageField(upload_to='seller_profiles', help_text="Upload your profile picture for our about page", blank=True, null=True)
    bio_description = models.TextField(max_length=500, default="", help_text="Brief bio describing who you are and what you do")
    seller_full_name = models.CharField(max_length=50)
    seller_listing_name = models.CharField(max_length=50)
    email = models.EmailField(max_length=50)
    date_added = models.DateField(auto_now_add=True)
    slug = models.SlugField(null=True, unique=True)
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return self.seller_listing_name


class Category(models.Model):
    name = models.CharField(max_length=30)
    slug = models.SlugField(null=False, unique=True)

    def __str__(self):
        return self.name
    
    class Meta:
        verbose_name_plural = "Categories"


# Create your models here.
class Product(models.Model):
    product_id = models.AutoField(primary_key=True)
    product_name = models.CharField(max_length=30, help_text="Limit 30 characters")
    slug = models.SlugField(unique=True, null=True)
    seller = models.ForeignKey(Seller, on_delete=models.CASCADE, null=True, blank=True)
    category = models.ManyToManyField(Category, help_text="Hold down “Control”, or “Command” on a Mac, to select more than one.")
    price = models.DecimalField(max_digits=6, decimal_places=2)
    shipping_cost = models.DecimalField(max_digits=6, decimal_places=2)
    description_short = models.TextField(max_length=100, default="", help_text="Limit 100 characters: Brief discription of the item")
    description_full = models.TextField(max_length=1000, default="", help_text="Your full item description when item details are viewed")
    product_image = models.ImageField(upload_to='product_images', help_text="There are no image size restrictions, but sqaure images will always render without any cropping.")
    date_listed = models.DateTimeField(auto_now_add=True)
    quantity = models.PositiveIntegerField(help_text="Quantity available - Default 1", default=1)
    total_purchases = models.PositiveIntegerField(default=0)

    def __str__(self):
        return self.product_name

    def save(self, **kwargs):
        slug_str = "%s" % (self.product_name) 
        unique_slugify(self, slug_str) 
        super(Product, self).save(**kwargs)


class ProductReview(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, null=True, blank=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    rating = models.PositiveIntegerField(default=5)
    subject = models.CharField(max_length=75, null=True, blank=True)
    comment = models.TextField(max_length=500, null=True, blank=True)
    timestamp = models.DateField(auto_now_add=True)

cloudland/sellers/forms.py
from django import forms
from store.models import Product, Seller

from crispy_forms.bootstrap import AppendedText, PrependedText
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, ButtonHolder, Submit
from crispy_forms.layout import Field


class ProductEditForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ['product_name', 'category', 'price', 'shipping_cost', 'description_short', 'description_full', 'product_image', 'quantity']

    def __init__(self, *args, **kwargs):
        super(ProductEditForm, self).__init__(*args, **kwargs)
        self.fields['description_short'].widget.attrs.update({
            'rows':'2'})
        self.fields['quantity'].widget.attrs.update({
            'class': 'form-control',
            'placeholder': '0',
            'type': 'text'})
        self.fields['price'].widget.attrs.update({
            'label': 'Price',
            'class': 'form-control',
            'placeholder': '0.00',
            'type': 'text'})
        self.fields['shipping_cost'].widget.attrs.update({
            'label': 'Shipping Price',
            'placeholder': '0.00',
            'class': 'form-control',
            'type': 'text'})

class ProductAddForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ['product_name', 'category', 'price', 'shipping_cost', 'description_short', 'description_full', 'product_image', 'quantity', 'seller']

    def __init__(self, *args, **kwargs):
        super(ProductAddForm, self).__init__(*args, **kwargs)
        self.fields['description_short'].widget.attrs.update({
            'rows':'2'})
        self.fields['quantity'].widget.attrs.update({
            'class': 'form-control',
            'placeholder': '0',
            'type': 'text'})
        self.fields['price'].widget.attrs.update({
            'label': 'Price',
            'placeholder': '0.00',
            'class': 'form-control',
            'type': 'text'})
        self.fields['shipping_cost'].widget.attrs.update({
            'label': 'Shipping Price',
            'placeholder': '0.00',
            'class': 'form-control',
            'type': 'text'})


class SellerBioEditForm(forms.ModelForm):
    class Meta:
        model = Seller
        fields = ['seller_full_name', 'seller_listing_name', 'profile_picture', 'bio_description', 'email']

    def __init__(self, *args, **kwargs):
        super(SellerBioEditForm, self).__init__(*args, **kwargs)
        self.fields['seller_full_name'].widget.attrs.update({
            'label': 'Full Name',
            'class': 'form-control',
            'placeholder': 'Your name',
            'type': 'text'})
        self.fields['seller_listing_name'].widget.attrs.update({
            'label': 'Listing Name',
            'class': 'form-control',
            'placeholder': 'Your listing name',
            'type': 'text'})
        self.fields['bio_description'].widget.attrs.update({
            'label': 'Bio',
            'class': 'form-control',
            'placeholder': 'Bio...',
            'type': 'text'})
        self.fields['email'].widget.attrs.update({
            'label': 'Email',
            'class': 'form-control',
            'placeholder': 'email@example.com',
            'type': 'email'})

cloudland/sellers/views.py
from django import forms
from django.conf import settings
from django.urls import reverse
from django.contrib import messages
from django.contrib.auth.models import User
from django.shortcuts import render, redirect, Http404, HttpResponseRedirect, get_object_or_404
from django.contrib.auth import login as auth_login
from django.contrib.auth import authenticate, logout
from django.contrib.auth.decorators import login_required

from accounts.forms import UsersLoginForm
from store.models import Product, Seller, Category
from .forms import ProductAddForm, ProductEditForm, SellerBioEditForm

# Verifies the user is in Seller group
def test_request(request):
    # previous_url = request.META.get('HTTP_REFERER')
    if request.user.groups.filter(name='Seller').count() == 0:
        return False
    return True


def seller_dashboard(request):
    if not test_request(request):
        raise Http404
    else:
        seller = Seller.objects.get(user=request.user)
        products = Product.objects.filter(seller=seller)
        args = {
            'products': products,
            'seller': seller,
        }
        return render(request, 'sellers/dashboard.html', args)

def add_product(request):
    if not test_request(request):
        raise Http404
    else:
        seller = Seller.objects.get(user=request.user)
        form = ProductAddForm(request.POST or None, request.FILES or None)
        if form.is_valid():
            form = form.save(commit=False)
            form.seller = seller
            form.save()

            # Now we add the categies once the object exists
            new_product = Product.objects.get(product_id=form.product_id) 
            categories = [int(i) for i in request.POST.getlist('category')]
            for c in categories:
                addCategory = Category.objects.get(id=c)
                new_product.category.add(addCategory)
                new_product.save()

            return redirect(reverse('seller-dashboard'))
        args = {
            'form': form,
            'seller_listing_name': seller.seller_listing_name,
        }
        return render(request, 'sellers/product-add.html', args)

def delete_product(request, id):
    if not test_request(request):
        raise Http404
    else:
        seller = Seller.objects.get(user=request.user)
        instance = get_object_or_404(Product, product_id=id)
        if instance.seller.id != seller.id:
            raise Http404
        else:
            instance.delete()
        return redirect(reverse('seller-dashboard'))

def edit_product(request, slug):
    if not test_request(request):
        raise Http404
    else:
        seller = Seller.objects.get(user=request.user)
        instance = get_object_or_404(Product, slug=slug)
        if instance.seller.id != seller.id:
            raise Http404
        form = ProductEditForm(request.POST or None, request.FILES or None, instance=instance)
        if form.is_valid():
            form.save()
            return redirect(reverse('seller-dashboard'))
        args = {
            'form': form,
            'product': instance,
        }
        return render(request, 'sellers/product-edit.html', args)

def edit_bio(request, slug):
    if not test_request(request):
        raise Http404
    else:
        seller = Seller.objects.get(user=request.user)
        instance = get_object_or_404(Seller, slug=slug)
        form = SellerBioEditForm(request.POST or None, request.FILES or None, instance=instance)
        if form.is_valid():
            form.save()
            return redirect(reverse('seller-dashboard'))
        args = {
            'form': form,
            'seller': seller,
        }
        return render(request, 'sellers/seller-bio-edit.html', args)

def seller_login(request):
    if request.method == 'POST':
        form = UsersLoginForm(request.POST or None)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username = username, password = password)
            if user.groups.filter(name='Seller').count():
                auth_login(request, user)
                next_url = request.GET.get('next')
                if next_url:
                    return redirect(next_url)
                else:
                    return redirect(reverse('seller-dashboard'))
            else:
                messages.warning(request, "Your account does not have the proper permission, please login here. If this is a mistake please contact us at cloudlandonline@gmail.com")
                return redirect(reverse('accounts-login'))
    # else render login page
    else:
        form = UsersLoginForm()
    return render(request, 'sellers/login.html', {'form': form})

cloudland/sellers/templates/sellers/product-add.html
<!-- Extends base template  -->
{% extends "store/base.html" %}
<!-- Crispy forms for styling -->
{% load crispy_forms_tags %}
<!-- Loads static content to access content in static directory -->
{% load static %}
<!-- Page title for window tab -->
{% block page %}Dashboard{% endblock page%}
<!-- Custom style sheet -->
{% block styles %}
<link href="{% static 'sellers/css/product-edit-styles.css' %}" rel="stylesheet"> {% endblock styles %}
<!-- fills content block in base template -->
{% block content %}
<div class="container">
    <h2>Add a New Product</h2>
    <hr>
    <div class="row">
        <div class="col-md-6 order-2" style="font-size: 1.2rem;">
            <h3 class="text-muted text-center">Preview</h3>
            <a class="card rounded-0 border-0 product-card">
                <div class="img-wrapper">
                    <div class="image">
                        <img class="card-img-top rounded-0 img-responsive" src="{{ product.product_image.url }}" id="card-image" alt="Product Image">
                    </div>
                </div>
                <div class="card-body text-left">
                    <h3 class="card-title">
                        <a id="product_name">{{ product.product_name }}</a>
                    </h3>
                    <p class="" id="seller-name">{{seller_listing_name}}</p>
                    <p class="card-text" id="description_short" style="margin-top: -1rem;">{{ product.description_short }}</p>
                    <h5 id="price">${{ product.price | floatformat:2 }}</h5>
                </div>
            </a>
            <h2 class="mt-5">Description</h2>
            <p id="description_full">{{ product.description_full }}</p>
            <h2>Shipping</h2>
            <table class="table table-borderless" style="font-size: 1rem;">
                <thead class="thead-light">
                    <tr>
                        <th scope="col">Type</th>
                        <th scope="col">Estimated Delivery</th>
                        <th scope="col">Product Shipping</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td scope="row">Standard Ground</td>
                        <td>5-10 business days</td>
                        <td id="shipping_cost">${{ product.shipping_cost }}</td>
                    </tr>
                </tbody>
            </table>
        </div>
        <div class="col-md-6 order-1">
            <form method="POST" enctype='multipart/form-data'>
                {% csrf_token %}
                <div class="form-group" onkeyup="func('product_name')">
                    <!-- Product name -->
                    {{ form.product_name|as_crispy_field }}
                </div>
                <div class="form-group" onkeyup="func('category')">
                    <!-- Category -->
                    {{ form.category|as_crispy_field }}
                </div>
                <div class="form-row justify-content-center">
                    <div class="form-group col-6" onkeyup="func('price')">
                        <!-- Price -->
                        <label for="id_price" class="requiredField">
                                Price<span class="asteriskField">*</span>
                            </label>
                        <div class="input-group mb-2">
                            <div class="input-group-prepend">
                                <div class="input-group-text bg-success text-white">$</div>
                            </div>
                            {{ form.price }}
                        </div>
                    </div>
                    <div class="form-group col-6">
                        <div class="form-group" onkeyup="func('shipping_cost')">
                            <!-- Shipping -->
                            <label for="id_price" class="requiredField">
                                    Shipping Price<span class="asteriskField">*</span>
                                </label>
                            <div class="input-group mb-2">
                                <div class="input-group-prepend">
                                    <div class="input-group-text bg-success text-white">$</div>
                                </div>
                                {{ form.shipping_cost }}
                            </div>
                        </div>
                    </div>
                </div>
                <div class="form-group" onkeyup="func('description_short')">
                    <!-- Short Description -->
                    {{ form.description_short|as_crispy_field }}
                </div>
                <div class="form-group" onkeyup="func('description_full')">
                    <!-- Full Description -->
                    {{ form.description_full|as_crispy_field }}
                </div>
                <div class="form-group" onkeyup="func('product_image')">
                    <!-- Image -->
                    {{ form.product_image}}
                    <small id="hint_id_description_full" class="form-text text-muted">We do not restrict image upload dimensions. To prevent cropping, we recommend a square image or a 2:3 (w:h) aspect ratio.</small>
                </div>

                <!-- Quantity -->
                <div class="form-group col-3 pl-0" onkeyup="func('quantity')">
                    <label for="id_quantity" class="requiredField">
                            Quantity<span class="asteriskField">*</span>
                        </label>
                    <div class="input-group mb-2">
                        {{ form.quantity }}
                    </div>
                </div>

                <div class="text-right my-3">
                    <a href="{% url 'seller-dashboard' %}" class="btn btn-danger">Cancel</a>
                    <button class="btn btn-success px-5" type="submit">Save</button>
                </div>
            </form>
        </div>
    </div>
    <script>
        function func(id) {
            update = document.getElementsByName(id)[0].value;
            if (id == 'price' || id == 'shipping_cost') {
                update = '$' + update;
            }
            document.getElementById(id).innerHTML = update;
        }

        // Handles image previewing 
        function previewImg(input) {
            if (input.files && input.files[0]) {
                var reader = new FileReader();

                reader.onload = function(e) {
                    $('#card-image').attr('src', e.target.result);
                }

                reader.readAsDataURL(input.files[0]); // convert to base64 string
            }
        }
        $("#id_product_image").change(function() {
            previewImg(this);
        });
    </script>
</div>
{% endblock content %}

cloudland/sellers/templates/sellers/product-edit.html
<!-- Extends base template  -->
{% extends "store/base.html" %}
<!-- Crispy forms for styling -->
{% load crispy_forms_tags %}
<!-- Loads static content to access content in static directory -->
{% load static %}
<!-- Page title for window tab -->
{% block page %}Dashboard{% endblock page%}
<!-- Custom style sheet -->
{% block styles %}
<link href="{% static 'sellers/css/product-edit-styles.css' %}" rel="stylesheet"> {% endblock styles %}
<!-- fills content block in base template -->
{% block content %}
<div class="container">
    <h2>Editing {{ product.product_name}}</h2>
    <hr>
    <div class="row">
        <div class="col-md-6 order-2" style="font-size: 1.2rem;">
            <h3 class="text-muted text-center">Preview</h3>
            <a class="card rounded-0 border-0 product-card">
                <div class="img-wrapper">
                    <div class="image">
                        <img class="card-img-top rounded-0 img-responsive" src="{{ product.product_image.url }}" id="card-image" alt="Product Image">
                    </div>
                </div>
                <div class="card-body text-left">
                    <h3 class="card-title">
                        <a id="product_name">{{ product.product_name }}</a>
                    </h3>
                    <p id="seller-name">// {{product.seller.seller_listing_name }} //</p>
                    <p class="card-text" id="description_short" style="margin-top: -1rem;">{{ product.description_short }}</p>
                    <h5 id="price">${{ product.price | floatformat:2 }}</h5>
                </div>
            </a>
            <h2 class="mt-5">Description</h2>
            <p id="description_full">{{ product.description_full }}</p>
            <h2>Shipping</h2>
            <table class="table table-borderless" style="font-size: 1rem;">
                <thead class="thead-light">
                    <tr>
                        <th scope="col">Type</th>
                        <th scope="col">Estimated Delivery</th>
                        <th scope="col">Product Shipping</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td scope="row">Standard Ground</td>
                        <td>5-10 business days</td>
                        <td id="shipping_cost">${{ product.shipping_cost }}</td>
                    </tr>
                </tbody>
            </table>
        </div>
        <div class="col-md-6 order-1">
            <form method="POST" enctype='multipart/form-data'>
                {% csrf_token %}
                <div class="form-group" onkeyup="func('product_name')">
                    <!-- Product name -->
                    {{ form.product_name|as_crispy_field }}
                </div>
                <div class="form-group" onkeyup="func('category')">
                    <!-- Category -->
                    {{ form.category|as_crispy_field }}
                </div>
                <div class="form-row">
                    <div class="form-group col-6" onkeyup="func('price')">
                        <!-- Price -->
                        <label for="id_price" class="requiredField">
                            Price<span class="asteriskField">*</span>
                        </label>
                        <div class="input-group mb-2">
                            <div class="input-group-prepend">
                                <div class="input-group-text bg-success text-white">$</div>
                            </div>
                            {{ form.price }}
                        </div>
                    </div>
                    <div class="form-group col-6">
                        <div class="form-group" onkeyup="func('shipping_cost')">
                            <!-- Shipping -->
                            <label for="id_price" class="requiredField">
                                Shipping Price<span class="asteriskField">*</span>
                            </label>
                            <div class="input-group mb-2">
                                <div class="input-group-prepend">
                                    <div class="input-group-text bg-success text-white">$</div>
                                </div>
                                {{ form.shipping_cost }}
                            </div>
                        </div>
                    </div>
                </div>
                <div class="form-group" onkeyup="func('description_short')">
                    <!-- Short Description -->
                    {{ form.description_short|as_crispy_field }}
                </div>
                <div class="form-group" onkeyup="func('description_full')">
                    <!-- Full Description -->
                    {{ form.description_full|as_crispy_field }}
                </div>
                <div class="form-group" onkeyup="func('product_image')" style="font-size: 1.1rem;">
                    <!-- Image -->
                    {{ form.product_image}}
                    <small id="hint_id_description_full" class="form-text text-muted">We do not restrict image upload dimensions. To prevent cropping, we recommend a square image or a 2:3 (w:h) aspect ratio.</small>
                </div>


                <!-- Quantity -->
                <div class="form-group col-3 pl-0" onkeyup="func('quantity')">
                    <label for="id_quantity" class="requiredField">
                            Quantity<span class="asteriskField">*</span>
                        </label>
                    <div class="input-group mb-2">
                        {{ form.quantity }}
                    </div>
                </div>

                <div class="text-right my-3">
                    <a href="{% url 'seller-dashboard' %}" class="btn btn-danger">Cancel</a>
                    <button class="btn btn-success px-5" type="submit">Save</button>
                </div>
            </form>
        </div>
    </div>
    <script>
        function func(id) {
            update = document.getElementsByName(id)[0].value;
            if (id == 'price' || id == 'shipping_cost') {
                update = '$' + update;
            }
            document.getElementById(id).innerHTML = update;
        }

        // Handles image previewing 
        function previewImg(input) {
            if (input.files && input.files[0]) {
                var reader = new FileReader();

                reader.onload = function(e) {
                    $('#card-image').attr('src', e.target.result);
                }

                reader.readAsDataURL(input.files[0]); // convert to base64 string
            }
        }
        $("#id_product_image").change(function() {
            previewImg(this);
        });
    </script>
</div>
{% endblock content %}

cloudland/sellers/templates/sellers/seller-bio-edit.html
<!-- Extends base template  -->
{% extends "store/base.html" %}
<!-- Crispy forms for styling -->
{% load crispy_forms_tags %}
<!-- Loads static content to access content in static directory -->
{% load static %}
<!-- Page title for window tab -->
{% block page %}Dashboard{% endblock page%}
<!-- Custom style sheet -->
{% block styles %}
<link href="{% static 'sellers/css/bio-edit-styles.css' %}" rel="stylesheet"> {% endblock styles %}
<!-- fills content block in base template -->
{% block content %}

<div class="container">
    <div class="col-md-12 m-auto">
        <h2>Edit My Bio</h2>
        <hr>
        <div class="row">
            <div class="col-md-6 order-2">
                <h3 class="text-muted text-center">Preview</h3>
                <div class="card border-0">
                    <img id="profile_picture" class="card-img-top" src="{{ seller.profile_picture.url }}" alt="{{ seller.seller_listing_name }} Profile Picture">
                    <div class="card-body text-left">
                        <div class="text-center">
                            <h3 id="seller_full_name" class="card-title mb-0">{{ seller.seller_full_name }}</h3>
                            <h5 id="seller_listing_name" class="card-text text-secondary">// {{ seller.seller_listing_name }} //</h5>
                            <h5 id="email" class="card-text text-black-50"><i class="fas fa-envelope fa-xs"></i> {{ seller.email }}</h5>
                        </div>
                        <p id="bio_description" class="p-2">{{ seller.bio_description }}</p>
                    </div>
                </div>
            </div>
            <div class="col-md-6 order-1">
                <form method="POST" enctype='multipart/form-data'>
                    {% csrf_token %}
                    <div class="form-group" onkeyup="func('seller_full_name')">
                        <!-- Full name -->
                        <label for="id_seller_full_name" class="requiredField">
                            Full Name<span class="asteriskField">*</span>
                        </label> {{ form.seller_full_name }}
                    </div>
                    <div class="form-group" onkeyup="func('seller_listing_name')">
                        <!-- Listing name -->
                        <label for="id_seller_full_name" class="requiredField">
                            Listing Name<span class="asteriskField">*</span>
                        </label> {{ form.seller_listing_name }}
                    </div>
                    <div class="form-group" onkeyup="func('profile_picture')" style="font-size: 1.1rem;">
                        <!-- Profile Picture -->
                        {{ form.profile_picture }}
                    </div>
                    <div class="form-group" onkeyup="func('bio_description')">
                        <!-- Bio Description -->
                        {{ form.bio_description|as_crispy_field }}
                    </div>
                    <div class="form-group" onkeyup="func('email')">
                        <!-- Email -->
                        {{ form.email|as_crispy_field }}
                    </div>
                    <div class="text-right my-2">
                        <a href="{% url 'seller-dashboard' %}" class="btn btn-danger">Cancel</a>
                        <button class="btn btn-success px-5" type="submit">Save</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
    <script>
        function func(id) {
            update = document.getElementsByName(id)[0].value;
            if (id == 'seller_listing_name') {
                update = '// ' + update + ' //';
            }
            document.getElementById(id).innerHTML = update;
        }

        // Handles image previewing 
        function previewImg(input) {
            if (input.files && input.files[0]) {
                var reader = new FileReader();

                reader.onload = function(e) {
                    $('#profile_picture').attr('src', e.target.result);
                }

                reader.readAsDataURL(input.files[0]); // convert to base64 string
            }
        }
        $("#id_profile_picture").change(function() {
            previewImg(this);
        });
    </script>
</div>
{% endblock content %}